---
- hosts: production

  # For initial provisioning
  # user: root

  # After ssh gets disabled for root
  user: deploy
  become: true

  vars:
    host: loaded.bike
    username: deploy
    password: $6$JguPtpmjzFyXQ.H6$R2q3ssJrYwpN3xDn3AbP2NeXc6cZ8OKLEzWZb3FXu6j1H/sLCXyqnggSZbOeL3hoxjQ8tkK83qf.XWOxJH9ap0
    public_key: ~/.ssh/id_rsa.pub
    database: "loaded_bike_prod"

    swapfile_location: /swapfile
    swapfile_size: 1G
    swapfile_swappiness: 10
    swapfile_vfs_cache_pressure: 50

  # server won't have python installed the first time around
  # gather_facts: no
  # pre_tasks:
  #  - name: Install python
  #    raw: apt-get -y install python-simplejson

  roles:
    - common
    - swap
    - ufw
    - user
    - nginx
    - elixir
    - node
    - postgresql
    - ssh
