---
- hosts: production
  user: root

  vars:
    host: loaded.bike
    username: deploy
    password: 1cfDQb6fECjNHYvbJnpX
    public_key: ~/.ssh/id_rsa.pub
    database: "loaded_bike_prod"

  # server won't have python installed the first time around
  gather_facts: no
  pre_tasks:
    - name: Install python
      raw: apt-get -y install python-simplejson

  roles:
    - common
    - ufw
    - user
    - nginx
    - elixir
    - node
    - postgresql
