---
- name: Gather facts
  setup:

- name: Install build tools
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - build-essential
    - git
    - unattended-upgrades
